language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export TEST_TYPE="unit"; bash ./gradlew check; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ $API_KEY ]; then export TEST_TYPE="integ"; bash ./gradlew integTest; fi'

after_success:
  - ./gradlew jacocoTestReport coveralls
